/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AnalyticsData {
    totalValue: bigint;
    countriesActive: bigint;
    activeCards: bigint;
    redemptionRate: number;
}
export interface TreasuryStatus {
    currencyBreakdown: Array<[string, bigint]>;
    totalValue: bigint;
    liquidity: number;
    reserves: bigint;
    lastAudit: Time;
}
export type Time = bigint;
export interface GiftCard {
    id: string;
    status: Status;
    exportHistory: Array<ExportRecord>;
    exports: Array<Export>;
    value: bigint;
    termsAccepted: boolean;
    owner: string;
    cardType: GiftCardType;
    redemptionCount: bigint;
    code: string;
    analyticsData?: AnalyticsData;
    createdAt: Time;
    creationMetadata: string;
    mobileNumber: string;
    emails: Array<Email>;
    lastUpdatedBy: string;
    updatedAt: Time;
    emailHistory: Array<EmailRecord>;
    expirationDate: Time;
    barcode: string;
    currency: Currency;
    notes: string;
    originCountry: string;
    redemptionHistory: Array<Redemption>;
    copiesGenerated: bigint;
    qrCode: string;
}
export interface Shipment {
    id: string;
    trackingTimeline: Array<LocationUpdate>;
    cargoDetails: Array<CargoItem>;
    originPort: string;
    requester: string;
    assignedBy: string;
    departureDate: Time;
    vesselId: string;
    createdAt: Time;
    customsDocumentation: string;
    destinationPort: string;
    estimatedArrivalDate: Time;
    updatedAt: Time;
    currentStatus: ShipmentStatus;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface OmniMeshStatus {
    status: string;
    active: boolean;
    nodes: bigint;
    lastSync: Time;
}
export interface Quiz {
    id: string;
    title: string;
    passingScore: bigint;
    timeLimitMinutes: bigint;
    questionIds: Array<string>;
    courseId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ContactForm {
    id: string;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface ConnectionStatus {
    status: string;
    ping?: bigint;
    network: string;
    message: string;
    timestamp: Time;
    environment: string;
    canisterId: string;
    retries: bigint;
}
export interface QuizAttempt {
    id: string;
    userId: string;
    score: number;
    attemptDate: bigint;
    selectedAnswers: Array<bigint>;
    quizId: string;
    passed: boolean;
}
export interface EmailRecord {
    id: string;
    to: string;
    status: EmailStatus;
    timestamp: Time;
    cardId: string;
}
export interface AIStatus {
    status: string;
    lastUpdated: Time;
    error?: string;
    currentTask: string;
}
export interface Tokenomics {
    roadmap: string;
    complianceNotice: string;
    utility: string;
    contractLink: string;
    totalSupply: bigint;
    whitepaperLink: string;
    governance: string;
    symbol: string;
}
export interface ExportRecord {
    id: string;
    method: ExportMethod;
    user: string;
    timestamp: Time;
    cardId: string;
}
export interface Vessel {
    id: string;
    vesselType: string;
    name: string;
    description: string;
    image?: ExternalBlob;
    capacity: bigint;
}
export interface Email {
    id: string;
    to: string;
    status: EmailStatus;
    timestamp: Time;
    cardId: string;
}
export interface CargoItem {
    id: string;
    weight: number;
    containerNumber: string;
    description: string;
    quantity: bigint;
}
export interface InvestorInquiry {
    id: string;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface User {
    id: bigint;
    name: string;
    createdAt: Time;
    email: string;
    updatedAt: Time;
}
export interface Redemption {
    redeemedBy: string;
    deviceDetails: string;
    verificationData: string;
    currency: Currency;
    notes: string;
    timestamp: Time;
    amount: bigint;
    location: string;
}
export interface Service {
    id: string;
    name: string;
    description: string;
    details: string;
}
export interface CompanyInfo {
    leadershipQuote: string;
    metrics: {
        vessels: bigint;
        crew: bigint;
        countries: bigint;
        years: bigint;
    };
    tagline: string;
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface CareerInquiry {
    id: string;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface Export {
    id: string;
    method: ExportMethod;
    user: string;
    timestamp: Time;
    cardId: string;
}
export interface LocationUpdate {
    status: string;
    notes: string;
    timestamp: Time;
    location: string;
}
export interface DAOProposal {
    id: string;
    status: string;
    title: string;
    votesAgainst: bigint;
    votesFor: bigint;
    createdAt: Time;
    votingDeadline: Time;
    description: string;
}
export interface ShipVessel {
    id: bigint;
    telemetry: string;
    name: string;
}
export interface Question {
    id: string;
    correctIndex: bigint;
    difficulty: string;
    explanation: string;
    questionText: string;
    subjectId: string;
    courseId: string;
    options: Array<string>;
    topicId: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum Currency {
    btc = "btc",
    eth = "eth",
    eur = "eur",
    gbp = "gbp",
    usd = "usd",
    bgkd = "bgkd"
}
export enum EmailStatus {
    pending = "pending",
    sent = "sent",
    delivered = "delivered",
    failed = "failed",
    bounced = "bounced"
}
export enum ExportMethod {
    csv = "csv",
    pdf = "pdf",
    excel = "excel"
}
export enum GiftCardType {
    fiat = "fiat",
    hybrid = "hybrid",
    crypto = "crypto"
}
export enum ShipmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    inTransit = "inTransit",
    delivered = "delivered"
}
export enum Status {
    active = "active",
    expired = "expired",
    pending = "pending",
    redeemed = "redeemed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addAuditor(auditorPrincipal: string): Promise<void>;
    addCargoItem(shipmentId: string, cargoItem: CargoItem): Promise<void>;
    addExportRecord(cardId: string, method: ExportMethod, user: string): Promise<void>;
    addService(id: string, name: string, description: string, details: string): Promise<void>;
    addUser(name: string, email: string): Promise<void>;
    addVessel(id: string, name: string, vesselType: string, capacity: bigint, image: ExternalBlob | null, description: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGiftCard(id: string, code: string, value: bigint, currency: Currency, cardType: GiftCardType, owner: string, notes: string, expirationDate: Time, originCountry: string, mobileNumber: string, createdBy: string, creationMetadata: string, lastUpdatedBy: string): Promise<void>;
    createQuestion(id: string, courseId: string, subjectId: string, topicId: string, questionText: string, options: Array<string>, correctIndex: bigint, explanation: string, difficulty: string): Promise<void>;
    createQuiz(id: string, title: string, courseId: string, questionIds: Array<string>, timeLimitMinutes: bigint, passingScore: bigint): Promise<void>;
    createShipment(originPort: string, destinationPort: string, vesselId: string, cargoDetails: Array<CargoItem>, departureDate: Time, estimatedArrivalDate: Time, customsDocumentation: string, requester: string): Promise<void>;
    deleteQuestion(id: string): Promise<void>;
    deleteQuiz(id: string): Promise<void>;
    generateZkSolvencyProof(): Promise<string>;
    getAIStatus(): Promise<AIStatus>;
    getAllQuestions(): Promise<Array<Question>>;
    getAllQuizzes(): Promise<Array<Quiz>>;
    getAllShipments(): Promise<Array<Shipment>>;
    getAllUsers(): Promise<Array<User>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCanisterInfo(): Promise<string>;
    getCareerInquiries(): Promise<Array<CareerInquiry>>;
    getCompanyInfo(): Promise<CompanyInfo | null>;
    getConnectionStatus(): Promise<ConnectionStatus>;
    getContactForms(): Promise<Array<ContactForm>>;
    getCyclesBalance(): Promise<bigint>;
    getDaoProposals(): Promise<Array<DAOProposal>>;
    getGiftCardAnalytics(): Promise<AnalyticsData>;
    getGiftCardById(id: string): Promise<GiftCard | null>;
    getGiftCards(): Promise<Array<GiftCard>>;
    getInvestorInquiries(): Promise<Array<InvestorInquiry>>;
    getMyVessels(): Promise<Array<ShipVessel>>;
    getNetworkInfo(): Promise<string>;
    getOmniMeshStatus(): Promise<OmniMeshStatus>;
    getPublicDemoShips(): Promise<Array<ShipVessel>>;
    getQuestionById(id: string): Promise<Question | null>;
    getQuestionsByCourse(courseId: string): Promise<Array<Question>>;
    getQuizById(id: string): Promise<Quiz | null>;
    getQuizzesByCourse(courseId: string): Promise<Array<Quiz>>;
    getRegistryCount(): Promise<bigint>;
    getServices(): Promise<Array<Service>>;
    getShipmentById(id: string): Promise<Shipment | null>;
    getShipmentsByVessel(vesselId: string): Promise<Array<Shipment>>;
    getTokenomics(): Promise<Tokenomics | null>;
    getTotalUsers(): Promise<bigint>;
    getTreasuryStatus(): Promise<TreasuryStatus>;
    getUniversalLaunchState(): Promise<boolean>;
    getUserAttempts(userId: string): Promise<Array<QuizAttempt>>;
    getUserById(id: bigint): Promise<User>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVessels(): Promise<Array<Vessel>>;
    getVesselsByType(vesselType: string): Promise<Array<Vessel>>;
    getZkCurrentRoot(): Promise<string>;
    healthCheck(): Promise<string>;
    initializeAccessControl(): Promise<void>;
    initializeAdminAccessControl(adminPrincipals: Array<string>): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    recordEmailSend(cardId: string, to: string, status: EmailStatus): Promise<void>;
    recordRedemption(cardId: string, location: string, amount: bigint, currency: Currency, redeemedBy: string, notes: string, verificationData: string, deviceDetails: string): Promise<void>;
    registerMyVessel(vesselName: string): Promise<boolean>;
    removeAuditor(auditorPrincipal: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedUsersDefault(): Promise<void>;
    setCompanyInfo(name: string, tagline: string, address: string, phone: string, email: string, vessels: bigint, crew: bigint, countries: bigint, years: bigint, leadershipQuote: string): Promise<void>;
    setTokenomics(totalSupply: bigint, symbol: string, governance: string, utility: string, roadmap: string, complianceNotice: string, whitepaperLink: string, contractLink: string): Promise<void>;
    submitCareerInquiry(name: string, email: string, message: string): Promise<void>;
    submitContactForm(name: string, email: string, message: string): Promise<void>;
    submitInvestorInquiry(name: string, email: string, message: string): Promise<void>;
    submitQuizAttempt(userId: string, quizId: string, selectedAnswers: Array<bigint>): Promise<QuizAttempt>;
    submitStcwQuiz(answers: Array<bigint>): Promise<{
        vesselsUnlocked: bigint;
        score: bigint;
        passed: boolean;
    }>;
    toggleUniversalLaunch(): Promise<void>;
    updateGiftCardStatus(id: string, newStatus: Status): Promise<void>;
    updateQuestion(id: string, courseId: string, subjectId: string, topicId: string, questionText: string, options: Array<string>, correctIndex: bigint, explanation: string, difficulty: string): Promise<void>;
    updateQuiz(id: string, title: string, courseId: string, questionIds: Array<string>, timeLimitMinutes: bigint, passingScore: bigint): Promise<void>;
    updateShipmentStatus(shipmentId: string, newStatus: ShipmentStatus, location: string, notes: string): Promise<void>;
    validatePrincipal(principal: Principal): Promise<boolean>;
    voteOnProposal(proposalId: string, support: boolean): Promise<void>;
}
import type { AIStatus as _AIStatus, AnalyticsData as _AnalyticsData, CargoItem as _CargoItem, CompanyInfo as _CompanyInfo, ConnectionStatus as _ConnectionStatus, Currency as _Currency, Email as _Email, EmailRecord as _EmailRecord, EmailStatus as _EmailStatus, Export as _Export, ExportMethod as _ExportMethod, ExportRecord as _ExportRecord, ExternalBlob as _ExternalBlob, GiftCard as _GiftCard, GiftCardType as _GiftCardType, LocationUpdate as _LocationUpdate, Question as _Question, Quiz as _Quiz, Redemption as _Redemption, Shipment as _Shipment, ShipmentStatus as _ShipmentStatus, Status as _Status, Time as _Time, Tokenomics as _Tokenomics, UserProfile as _UserProfile, UserRole as _UserRole, Vessel as _Vessel, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addAuditor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAuditor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAuditor(arg0);
            return result;
        }
    }
    async addCargoItem(arg0: string, arg1: CargoItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCargoItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCargoItem(arg0, arg1);
            return result;
        }
    }
    async addExportRecord(arg0: string, arg1: ExportMethod, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExportRecord(arg0, to_candid_ExportMethod_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExportRecord(arg0, to_candid_ExportMethod_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async addService(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0, arg1);
            return result;
        }
    }
    async addVessel(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: ExternalBlob | null, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVessel(arg0, arg1, arg2, arg3, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVessel(arg0, arg1, arg2, arg3, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGiftCard(arg0: string, arg1: string, arg2: bigint, arg3: Currency, arg4: GiftCardType, arg5: string, arg6: string, arg7: Time, arg8: string, arg9: string, arg10: string, arg11: string, arg12: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGiftCard(arg0, arg1, arg2, to_candid_Currency_n14(this._uploadFile, this._downloadFile, arg3), to_candid_GiftCardType_n16(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGiftCard(arg0, arg1, arg2, to_candid_Currency_n14(this._uploadFile, this._downloadFile, arg3), to_candid_GiftCardType_n16(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            return result;
        }
    }
    async createQuestion(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>, arg6: bigint, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuestion(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuestion(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async createQuiz(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createShipment(arg0: string, arg1: string, arg2: string, arg3: Array<CargoItem>, arg4: Time, arg5: Time, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createShipment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShipment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async deleteQuestion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return result;
        }
    }
    async deleteQuiz(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuiz(arg0);
            return result;
        }
    }
    async generateZkSolvencyProof(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateZkSolvencyProof();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateZkSolvencyProof();
            return result;
        }
    }
    async getAIStatus(): Promise<AIStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIStatus();
                return from_candid_AIStatus_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIStatus();
            return from_candid_AIStatus_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestions();
            return result;
        }
    }
    async getAllQuizzes(): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuizzes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuizzes();
            return result;
        }
    }
    async getAllShipments(): Promise<Array<Shipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShipments();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShipments();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanisterInfo(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterInfo();
            return result;
        }
    }
    async getCareerInquiries(): Promise<Array<CareerInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCareerInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCareerInquiries();
            return result;
        }
    }
    async getCompanyInfo(): Promise<CompanyInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyInfo();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyInfo();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConnectionStatus(): Promise<ConnectionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnectionStatus();
                return from_candid_ConnectionStatus_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnectionStatus();
            return from_candid_ConnectionStatus_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactForms(): Promise<Array<ContactForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactForms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactForms();
            return result;
        }
    }
    async getCyclesBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCyclesBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCyclesBalance();
            return result;
        }
    }
    async getDaoProposals(): Promise<Array<DAOProposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDaoProposals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDaoProposals();
            return result;
        }
    }
    async getGiftCardAnalytics(): Promise<AnalyticsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getGiftCardAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGiftCardAnalytics();
            return result;
        }
    }
    async getGiftCardById(arg0: string): Promise<GiftCard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGiftCardById(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGiftCardById(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGiftCards(): Promise<Array<GiftCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGiftCards();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGiftCards();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestorInquiries(): Promise<Array<InvestorInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestorInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestorInquiries();
            return result;
        }
    }
    async getMyVessels(): Promise<Array<ShipVessel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVessels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVessels();
            return result;
        }
    }
    async getNetworkInfo(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getNetworkInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNetworkInfo();
            return result;
        }
    }
    async getOmniMeshStatus(): Promise<OmniMeshStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getOmniMeshStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOmniMeshStatus();
            return result;
        }
    }
    async getPublicDemoShips(): Promise<Array<ShipVessel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicDemoShips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicDemoShips();
            return result;
        }
    }
    async getQuestionById(arg0: string): Promise<Question | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionById(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionById(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsByCourse(arg0: string): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByCourse(arg0);
            return result;
        }
    }
    async getQuizById(arg0: string): Promise<Quiz | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizById(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizById(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizzesByCourse(arg0: string): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizzesByCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizzesByCourse(arg0);
            return result;
        }
    }
    async getRegistryCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistryCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistryCount();
            return result;
        }
    }
    async getServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServices();
            return result;
        }
    }
    async getShipmentById(arg0: string): Promise<Shipment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShipmentById(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShipmentById(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShipmentsByVessel(arg0: string): Promise<Array<Shipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShipmentsByVessel(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShipmentsByVessel(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTokenomics(): Promise<Tokenomics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenomics();
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenomics();
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalUsers(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalUsers();
            return result;
        }
    }
    async getTreasuryStatus(): Promise<TreasuryStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreasuryStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreasuryStatus();
            return result;
        }
    }
    async getUniversalLaunchState(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniversalLaunchState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniversalLaunchState();
            return result;
        }
    }
    async getUserAttempts(arg0: string): Promise<Array<QuizAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAttempts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAttempts(arg0);
            return result;
        }
    }
    async getUserById(arg0: bigint): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVessels(): Promise<Array<Vessel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVessels();
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVessels();
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVesselsByType(arg0: string): Promise<Array<Vessel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVesselsByType(arg0);
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVesselsByType(arg0);
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getZkCurrentRoot(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getZkCurrentRoot();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZkCurrentRoot();
            return result;
        }
    }
    async healthCheck(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async initializeAdminAccessControl(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAdminAccessControl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAdminAccessControl(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordEmailSend(arg0: string, arg1: string, arg2: EmailStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordEmailSend(arg0, arg1, to_candid_EmailStatus_n70(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordEmailSend(arg0, arg1, to_candid_EmailStatus_n70(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async recordRedemption(arg0: string, arg1: string, arg2: bigint, arg3: Currency, arg4: string, arg5: string, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordRedemption(arg0, arg1, arg2, to_candid_Currency_n14(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordRedemption(arg0, arg1, arg2, to_candid_Currency_n14(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async registerMyVessel(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerMyVessel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerMyVessel(arg0);
            return result;
        }
    }
    async removeAuditor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAuditor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAuditor(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedUsersDefault(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedUsersDefault();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedUsersDefault();
            return result;
        }
    }
    async setCompanyInfo(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCompanyInfo(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCompanyInfo(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async setTokenomics(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTokenomics(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTokenomics(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async submitCareerInquiry(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCareerInquiry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCareerInquiry(arg0, arg1, arg2);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return result;
        }
    }
    async submitInvestorInquiry(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInvestorInquiry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInvestorInquiry(arg0, arg1, arg2);
            return result;
        }
    }
    async submitQuizAttempt(arg0: string, arg1: string, arg2: Array<bigint>): Promise<QuizAttempt> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAttempt(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAttempt(arg0, arg1, arg2);
            return result;
        }
    }
    async submitStcwQuiz(arg0: Array<bigint>): Promise<{
        vesselsUnlocked: bigint;
        score: bigint;
        passed: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitStcwQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitStcwQuiz(arg0);
            return result;
        }
    }
    async toggleUniversalLaunch(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleUniversalLaunch();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleUniversalLaunch();
            return result;
        }
    }
    async updateGiftCardStatus(arg0: string, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGiftCardStatus(arg0, to_candid_Status_n72(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGiftCardStatus(arg0, to_candid_Status_n72(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateQuestion(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>, arg6: bigint, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestion(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestion(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateQuiz(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuiz(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuiz(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateShipmentStatus(arg0: string, arg1: ShipmentStatus, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShipmentStatus(arg0, to_candid_ShipmentStatus_n74(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShipmentStatus(arg0, to_candid_ShipmentStatus_n74(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async validatePrincipal(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validatePrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validatePrincipal(arg0);
            return result;
        }
    }
    async voteOnProposal(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.voteOnProposal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteOnProposal(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AIStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AIStatus): AIStatus {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ConnectionStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConnectionStatus): ConnectionStatus {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Currency_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Currency): Currency {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_EmailRecord_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmailRecord): EmailRecord {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_EmailStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmailStatus): EmailStatus {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Email_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Email): Email {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_ExportMethod_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExportMethod): ExportMethod {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_ExportRecord_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExportRecord): ExportRecord {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Export_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Export): Export {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GiftCardType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GiftCardType): GiftCardType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_GiftCard_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GiftCard): GiftCard {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Redemption_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Redemption): Redemption {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_ShipmentStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShipmentStatus): ShipmentStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Shipment_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shipment): Shipment {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_Vessel_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vessel): Promise<Vessel> {
    return await from_candid_record_n67(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanyInfo]): CompanyInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GiftCard]): GiftCard | null {
    return value.length === 0 ? null : from_candid_GiftCard_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnalyticsData]): AnalyticsData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Question]): Question | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quiz]): Quiz | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Shipment]): Shipment | null {
    return value.length === 0 ? null : from_candid_Shipment_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tokenomics]): Tokenomics | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n69(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    lastUpdated: _Time;
    error: [] | [string];
    currentTask: string;
}): {
    status: string;
    lastUpdated: Time;
    error?: string;
    currentTask: string;
} {
    return {
        status: value.status,
        lastUpdated: value.lastUpdated,
        error: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.error)),
        currentTask: value.currentTask
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    trackingTimeline: Array<_LocationUpdate>;
    cargoDetails: Array<_CargoItem>;
    originPort: string;
    requester: string;
    assignedBy: string;
    departureDate: _Time;
    vesselId: string;
    createdAt: _Time;
    customsDocumentation: string;
    destinationPort: string;
    estimatedArrivalDate: _Time;
    updatedAt: _Time;
    currentStatus: _ShipmentStatus;
}): {
    id: string;
    trackingTimeline: Array<LocationUpdate>;
    cargoDetails: Array<CargoItem>;
    originPort: string;
    requester: string;
    assignedBy: string;
    departureDate: Time;
    vesselId: string;
    createdAt: Time;
    customsDocumentation: string;
    destinationPort: string;
    estimatedArrivalDate: Time;
    updatedAt: Time;
    currentStatus: ShipmentStatus;
} {
    return {
        id: value.id,
        trackingTimeline: value.trackingTimeline,
        cargoDetails: value.cargoDetails,
        originPort: value.originPort,
        requester: value.requester,
        assignedBy: value.assignedBy,
        departureDate: value.departureDate,
        vesselId: value.vesselId,
        createdAt: value.createdAt,
        customsDocumentation: value.customsDocumentation,
        destinationPort: value.destinationPort,
        estimatedArrivalDate: value.estimatedArrivalDate,
        updatedAt: value.updatedAt,
        currentStatus: from_candid_ShipmentStatus_n24(_uploadFile, _downloadFile, value.currentStatus)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    ping: [] | [bigint];
    network: string;
    message: string;
    timestamp: _Time;
    environment: string;
    canisterId: string;
    retries: bigint;
}): {
    status: string;
    ping?: bigint;
    network: string;
    message: string;
    timestamp: Time;
    environment: string;
    canisterId: string;
    retries: bigint;
} {
    return {
        status: value.status,
        ping: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.ping)),
        network: value.network,
        message: value.message,
        timestamp: value.timestamp,
        environment: value.environment,
        canisterId: value.canisterId,
        retries: value.retries
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    exportHistory: Array<_ExportRecord>;
    exports: Array<_Export>;
    value: bigint;
    termsAccepted: boolean;
    owner: string;
    cardType: _GiftCardType;
    redemptionCount: bigint;
    code: string;
    analyticsData: [] | [_AnalyticsData];
    createdAt: _Time;
    creationMetadata: string;
    mobileNumber: string;
    emails: Array<_Email>;
    lastUpdatedBy: string;
    updatedAt: _Time;
    emailHistory: Array<_EmailRecord>;
    expirationDate: _Time;
    barcode: string;
    currency: _Currency;
    notes: string;
    originCountry: string;
    redemptionHistory: Array<_Redemption>;
    copiesGenerated: bigint;
    qrCode: string;
}): {
    id: string;
    status: Status;
    exportHistory: Array<ExportRecord>;
    exports: Array<Export>;
    value: bigint;
    termsAccepted: boolean;
    owner: string;
    cardType: GiftCardType;
    redemptionCount: bigint;
    code: string;
    analyticsData?: AnalyticsData;
    createdAt: Time;
    creationMetadata: string;
    mobileNumber: string;
    emails: Array<Email>;
    lastUpdatedBy: string;
    updatedAt: Time;
    emailHistory: Array<EmailRecord>;
    expirationDate: Time;
    barcode: string;
    currency: Currency;
    notes: string;
    originCountry: string;
    redemptionHistory: Array<Redemption>;
    copiesGenerated: bigint;
    qrCode: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n36(_uploadFile, _downloadFile, value.status),
        exportHistory: from_candid_vec_n38(_uploadFile, _downloadFile, value.exportHistory),
        exports: from_candid_vec_n43(_uploadFile, _downloadFile, value.exports),
        value: value.value,
        termsAccepted: value.termsAccepted,
        owner: value.owner,
        cardType: from_candid_GiftCardType_n45(_uploadFile, _downloadFile, value.cardType),
        redemptionCount: value.redemptionCount,
        code: value.code,
        analyticsData: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.analyticsData)),
        createdAt: value.createdAt,
        creationMetadata: value.creationMetadata,
        mobileNumber: value.mobileNumber,
        emails: from_candid_vec_n48(_uploadFile, _downloadFile, value.emails),
        lastUpdatedBy: value.lastUpdatedBy,
        updatedAt: value.updatedAt,
        emailHistory: from_candid_vec_n53(_uploadFile, _downloadFile, value.emailHistory),
        expirationDate: value.expirationDate,
        barcode: value.barcode,
        currency: from_candid_Currency_n55(_uploadFile, _downloadFile, value.currency),
        notes: value.notes,
        originCountry: value.originCountry,
        redemptionHistory: from_candid_vec_n57(_uploadFile, _downloadFile, value.redemptionHistory),
        copiesGenerated: value.copiesGenerated,
        qrCode: value.qrCode
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    method: _ExportMethod;
    user: string;
    timestamp: _Time;
    cardId: string;
}): {
    id: string;
    method: ExportMethod;
    user: string;
    timestamp: Time;
    cardId: string;
} {
    return {
        id: value.id,
        method: from_candid_ExportMethod_n41(_uploadFile, _downloadFile, value.method),
        user: value.user,
        timestamp: value.timestamp,
        cardId: value.cardId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    to: string;
    status: _EmailStatus;
    timestamp: _Time;
    cardId: string;
}): {
    id: string;
    to: string;
    status: EmailStatus;
    timestamp: Time;
    cardId: string;
} {
    return {
        id: value.id,
        to: value.to,
        status: from_candid_EmailStatus_n51(_uploadFile, _downloadFile, value.status),
        timestamp: value.timestamp,
        cardId: value.cardId
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    redeemedBy: string;
    deviceDetails: string;
    verificationData: string;
    currency: _Currency;
    notes: string;
    timestamp: _Time;
    amount: bigint;
    location: string;
}): {
    redeemedBy: string;
    deviceDetails: string;
    verificationData: string;
    currency: Currency;
    notes: string;
    timestamp: Time;
    amount: bigint;
    location: string;
} {
    return {
        redeemedBy: value.redeemedBy,
        deviceDetails: value.deviceDetails,
        verificationData: value.verificationData,
        currency: from_candid_Currency_n55(_uploadFile, _downloadFile, value.currency),
        notes: value.notes,
        timestamp: value.timestamp,
        amount: value.amount,
        location: value.location
    };
}
async function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    vesselType: string;
    name: string;
    description: string;
    image: [] | [_ExternalBlob];
    capacity: bigint;
}): Promise<{
    id: string;
    vesselType: string;
    name: string;
    description: string;
    image?: ExternalBlob;
    capacity: bigint;
}> {
    return {
        id: value.id,
        vesselType: value.vesselType,
        name: value.name,
        description: value.description,
        image: record_opt_to_undefined(await from_candid_opt_n68(_uploadFile, _downloadFile, value.image)),
        capacity: value.capacity
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    inTransit: null;
} | {
    delivered: null;
}): ShipmentStatus {
    return "cancelled" in value ? ShipmentStatus.cancelled : "pending" in value ? ShipmentStatus.pending : "inTransit" in value ? ShipmentStatus.inTransit : "delivered" in value ? ShipmentStatus.delivered : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    expired: null;
} | {
    pending: null;
} | {
    redeemed: null;
}): Status {
    return "active" in value ? Status.active : "expired" in value ? Status.expired : "pending" in value ? Status.pending : "redeemed" in value ? Status.redeemed : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    csv: null;
} | {
    pdf: null;
} | {
    excel: null;
}): ExportMethod {
    return "csv" in value ? ExportMethod.csv : "pdf" in value ? ExportMethod.pdf : "excel" in value ? ExportMethod.excel : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fiat: null;
} | {
    hybrid: null;
} | {
    crypto: null;
}): GiftCardType {
    return "fiat" in value ? GiftCardType.fiat : "hybrid" in value ? GiftCardType.hybrid : "crypto" in value ? GiftCardType.crypto : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    sent: null;
} | {
    delivered: null;
} | {
    failed: null;
} | {
    bounced: null;
}): EmailStatus {
    return "pending" in value ? EmailStatus.pending : "sent" in value ? EmailStatus.sent : "delivered" in value ? EmailStatus.delivered : "failed" in value ? EmailStatus.failed : "bounced" in value ? EmailStatus.bounced : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    btc: null;
} | {
    eth: null;
} | {
    eur: null;
} | {
    gbp: null;
} | {
    usd: null;
} | {
    bgkd: null;
}): Currency {
    return "btc" in value ? Currency.btc : "eth" in value ? Currency.eth : "eur" in value ? Currency.eur : "gbp" in value ? Currency.gbp : "usd" in value ? Currency.usd : "bgkd" in value ? Currency.bgkd : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Shipment>): Array<Shipment> {
    return value.map((x)=>from_candid_Shipment_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExportRecord>): Array<ExportRecord> {
    return value.map((x)=>from_candid_ExportRecord_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Export>): Array<Export> {
    return value.map((x)=>from_candid_Export_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Email>): Array<Email> {
    return value.map((x)=>from_candid_Email_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmailRecord>): Array<EmailRecord> {
    return value.map((x)=>from_candid_EmailRecord_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Redemption>): Array<Redemption> {
    return value.map((x)=>from_candid_Redemption_n58(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GiftCard>): Array<GiftCard> {
    return value.map((x)=>from_candid_GiftCard_n34(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vessel>): Promise<Array<Vessel>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Vessel_n66(_uploadFile, _downloadFile, x)));
}
function to_candid_Currency_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): _Currency {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_EmailStatus_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmailStatus): _EmailStatus {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_ExportMethod_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExportMethod): _ExportMethod {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GiftCardType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GiftCardType): _GiftCardType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ShipmentStatus_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShipmentStatus): _ShipmentStatus {
    return to_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): {
    btc: null;
} | {
    eth: null;
} | {
    eur: null;
} | {
    gbp: null;
} | {
    usd: null;
} | {
    bgkd: null;
} {
    return value == Currency.btc ? {
        btc: null
    } : value == Currency.eth ? {
        eth: null
    } : value == Currency.eur ? {
        eur: null
    } : value == Currency.gbp ? {
        gbp: null
    } : value == Currency.usd ? {
        usd: null
    } : value == Currency.bgkd ? {
        bgkd: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GiftCardType): {
    fiat: null;
} | {
    hybrid: null;
} | {
    crypto: null;
} {
    return value == GiftCardType.fiat ? {
        fiat: null
    } : value == GiftCardType.hybrid ? {
        hybrid: null
    } : value == GiftCardType.crypto ? {
        crypto: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmailStatus): {
    pending: null;
} | {
    sent: null;
} | {
    delivered: null;
} | {
    failed: null;
} | {
    bounced: null;
} {
    return value == EmailStatus.pending ? {
        pending: null
    } : value == EmailStatus.sent ? {
        sent: null
    } : value == EmailStatus.delivered ? {
        delivered: null
    } : value == EmailStatus.failed ? {
        failed: null
    } : value == EmailStatus.bounced ? {
        bounced: null
    } : value;
}
function to_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    active: null;
} | {
    expired: null;
} | {
    pending: null;
} | {
    redeemed: null;
} {
    return value == Status.active ? {
        active: null
    } : value == Status.expired ? {
        expired: null
    } : value == Status.pending ? {
        pending: null
    } : value == Status.redeemed ? {
        redeemed: null
    } : value;
}
function to_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShipmentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} {
    return value == ShipmentStatus.cancelled ? {
        cancelled: null
    } : value == ShipmentStatus.pending ? {
        pending: null
    } : value == ShipmentStatus.inTransit ? {
        inTransit: null
    } : value == ShipmentStatus.delivered ? {
        delivered: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExportMethod): {
    csv: null;
} | {
    pdf: null;
} | {
    excel: null;
} {
    return value == ExportMethod.csv ? {
        csv: null
    } : value == ExportMethod.pdf ? {
        pdf: null
    } : value == ExportMethod.excel ? {
        excel: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
