/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CargoItem = IDL.Record({
  'id' : IDL.Text,
  'weight' : IDL.Float64,
  'containerNumber' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const ExportMethod = IDL.Variant({
  'csv' : IDL.Null,
  'pdf' : IDL.Null,
  'excel' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Currency = IDL.Variant({
  'btc' : IDL.Null,
  'eth' : IDL.Null,
  'eur' : IDL.Null,
  'gbp' : IDL.Null,
  'usd' : IDL.Null,
  'bgkd' : IDL.Null,
});
export const GiftCardType = IDL.Variant({
  'fiat' : IDL.Null,
  'hybrid' : IDL.Null,
  'crypto' : IDL.Null,
});
export const Time = IDL.Int;
export const AIStatus = IDL.Record({
  'status' : IDL.Text,
  'lastUpdated' : Time,
  'error' : IDL.Opt(IDL.Text),
  'currentTask' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'difficulty' : IDL.Text,
  'explanation' : IDL.Text,
  'questionText' : IDL.Text,
  'subjectId' : IDL.Text,
  'courseId' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'topicId' : IDL.Text,
});
export const Quiz = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'passingScore' : IDL.Nat,
  'timeLimitMinutes' : IDL.Nat,
  'questionIds' : IDL.Vec(IDL.Text),
  'courseId' : IDL.Text,
});
export const LocationUpdate = IDL.Record({
  'status' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'location' : IDL.Text,
});
export const ShipmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'inTransit' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Shipment = IDL.Record({
  'id' : IDL.Text,
  'trackingTimeline' : IDL.Vec(LocationUpdate),
  'cargoDetails' : IDL.Vec(CargoItem),
  'originPort' : IDL.Text,
  'requester' : IDL.Text,
  'assignedBy' : IDL.Text,
  'departureDate' : Time,
  'vesselId' : IDL.Text,
  'createdAt' : Time,
  'customsDocumentation' : IDL.Text,
  'destinationPort' : IDL.Text,
  'estimatedArrivalDate' : Time,
  'updatedAt' : Time,
  'currentStatus' : ShipmentStatus,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'updatedAt' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CareerInquiry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const CompanyInfo = IDL.Record({
  'leadershipQuote' : IDL.Text,
  'metrics' : IDL.Record({
    'vessels' : IDL.Nat,
    'crew' : IDL.Nat,
    'countries' : IDL.Nat,
    'years' : IDL.Nat,
  }),
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ConnectionStatus = IDL.Record({
  'status' : IDL.Text,
  'ping' : IDL.Opt(IDL.Int),
  'network' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'environment' : IDL.Text,
  'canisterId' : IDL.Text,
  'retries' : IDL.Nat,
});
export const ContactForm = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const DAOProposal = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'votesAgainst' : IDL.Nat,
  'votesFor' : IDL.Nat,
  'createdAt' : Time,
  'votingDeadline' : Time,
  'description' : IDL.Text,
});
export const AnalyticsData = IDL.Record({
  'totalValue' : IDL.Nat,
  'countriesActive' : IDL.Nat,
  'activeCards' : IDL.Nat,
  'redemptionRate' : IDL.Float64,
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'redeemed' : IDL.Null,
});
export const ExportRecord = IDL.Record({
  'id' : IDL.Text,
  'method' : ExportMethod,
  'user' : IDL.Text,
  'timestamp' : Time,
  'cardId' : IDL.Text,
});
export const Export = IDL.Record({
  'id' : IDL.Text,
  'method' : ExportMethod,
  'user' : IDL.Text,
  'timestamp' : Time,
  'cardId' : IDL.Text,
});
export const EmailStatus = IDL.Variant({
  'pending' : IDL.Null,
  'sent' : IDL.Null,
  'delivered' : IDL.Null,
  'failed' : IDL.Null,
  'bounced' : IDL.Null,
});
export const Email = IDL.Record({
  'id' : IDL.Text,
  'to' : IDL.Text,
  'status' : EmailStatus,
  'timestamp' : Time,
  'cardId' : IDL.Text,
});
export const EmailRecord = IDL.Record({
  'id' : IDL.Text,
  'to' : IDL.Text,
  'status' : EmailStatus,
  'timestamp' : Time,
  'cardId' : IDL.Text,
});
export const Redemption = IDL.Record({
  'redeemedBy' : IDL.Text,
  'deviceDetails' : IDL.Text,
  'verificationData' : IDL.Text,
  'currency' : Currency,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
  'location' : IDL.Text,
});
export const GiftCard = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'exportHistory' : IDL.Vec(ExportRecord),
  'exports' : IDL.Vec(Export),
  'value' : IDL.Nat,
  'termsAccepted' : IDL.Bool,
  'owner' : IDL.Text,
  'cardType' : GiftCardType,
  'redemptionCount' : IDL.Nat,
  'code' : IDL.Text,
  'analyticsData' : IDL.Opt(AnalyticsData),
  'createdAt' : Time,
  'creationMetadata' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'emails' : IDL.Vec(Email),
  'lastUpdatedBy' : IDL.Text,
  'updatedAt' : Time,
  'emailHistory' : IDL.Vec(EmailRecord),
  'expirationDate' : Time,
  'barcode' : IDL.Text,
  'currency' : Currency,
  'notes' : IDL.Text,
  'originCountry' : IDL.Text,
  'redemptionHistory' : IDL.Vec(Redemption),
  'copiesGenerated' : IDL.Nat,
  'qrCode' : IDL.Text,
});
export const InvestorInquiry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ShipVessel = IDL.Record({
  'id' : IDL.Nat,
  'telemetry' : IDL.Text,
  'name' : IDL.Text,
});
export const OmniMeshStatus = IDL.Record({
  'status' : IDL.Text,
  'active' : IDL.Bool,
  'nodes' : IDL.Nat,
  'lastSync' : Time,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'details' : IDL.Text,
});
export const Tokenomics = IDL.Record({
  'roadmap' : IDL.Text,
  'complianceNotice' : IDL.Text,
  'utility' : IDL.Text,
  'contractLink' : IDL.Text,
  'totalSupply' : IDL.Nat,
  'whitepaperLink' : IDL.Text,
  'governance' : IDL.Text,
  'symbol' : IDL.Text,
});
export const TreasuryStatus = IDL.Record({
  'currencyBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalValue' : IDL.Nat,
  'liquidity' : IDL.Float64,
  'reserves' : IDL.Nat,
  'lastAudit' : Time,
});
export const QuizAttempt = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Text,
  'score' : IDL.Float64,
  'attemptDate' : IDL.Int,
  'selectedAnswers' : IDL.Vec(IDL.Nat),
  'quizId' : IDL.Text,
  'passed' : IDL.Bool,
});
export const Vessel = IDL.Record({
  'id' : IDL.Text,
  'vesselType' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'capacity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAuditor' : IDL.Func([IDL.Text], [], []),
  'addCargoItem' : IDL.Func([IDL.Text, CargoItem], [], []),
  'addExportRecord' : IDL.Func([IDL.Text, ExportMethod, IDL.Text], [], []),
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addVessel' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(ExternalBlob), IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGiftCard' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Currency,
        GiftCardType,
        IDL.Text,
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createQuestion' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createQuiz' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'createShipment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(CargoItem),
        Time,
        Time,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteQuestion' : IDL.Func([IDL.Text], [], []),
  'deleteQuiz' : IDL.Func([IDL.Text], [], []),
  'generateZkSolvencyProof' : IDL.Func([], [IDL.Text], []),
  'getAIStatus' : IDL.Func([], [AIStatus], ['query']),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getAllQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
  'getAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterInfo' : IDL.Func([], [IDL.Text], ['query']),
  'getCareerInquiries' : IDL.Func([], [IDL.Vec(CareerInquiry)], ['query']),
  'getCompanyInfo' : IDL.Func([], [IDL.Opt(CompanyInfo)], ['query']),
  'getConnectionStatus' : IDL.Func([], [ConnectionStatus], ['query']),
  'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getDaoProposals' : IDL.Func([], [IDL.Vec(DAOProposal)], ['query']),
  'getGiftCardAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
  'getGiftCardById' : IDL.Func([IDL.Text], [IDL.Opt(GiftCard)], ['query']),
  'getGiftCards' : IDL.Func([], [IDL.Vec(GiftCard)], ['query']),
  'getInvestorInquiries' : IDL.Func([], [IDL.Vec(InvestorInquiry)], ['query']),
  'getMyVessels' : IDL.Func([], [IDL.Vec(ShipVessel)], ['query']),
  'getNetworkInfo' : IDL.Func([], [IDL.Text], ['query']),
  'getOmniMeshStatus' : IDL.Func([], [OmniMeshStatus], ['query']),
  'getPublicDemoShips' : IDL.Func([], [IDL.Vec(ShipVessel)], ['query']),
  'getQuestionById' : IDL.Func([IDL.Text], [IDL.Opt(Question)], ['query']),
  'getQuestionsByCourse' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getQuizById' : IDL.Func([IDL.Text], [IDL.Opt(Quiz)], ['query']),
  'getQuizzesByCourse' : IDL.Func([IDL.Text], [IDL.Vec(Quiz)], ['query']),
  'getRegistryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getShipmentById' : IDL.Func([IDL.Text], [IDL.Opt(Shipment)], ['query']),
  'getShipmentsByVessel' : IDL.Func([IDL.Text], [IDL.Vec(Shipment)], ['query']),
  'getTokenomics' : IDL.Func([], [IDL.Opt(Tokenomics)], ['query']),
  'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getTreasuryStatus' : IDL.Func([], [TreasuryStatus], ['query']),
  'getUniversalLaunchState' : IDL.Func([], [IDL.Bool], ['query']),
  'getUserAttempts' : IDL.Func([IDL.Text], [IDL.Vec(QuizAttempt)], ['query']),
  'getUserById' : IDL.Func([IDL.Nat], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVessels' : IDL.Func([], [IDL.Vec(Vessel)], ['query']),
  'getVesselsByType' : IDL.Func([IDL.Text], [IDL.Vec(Vessel)], ['query']),
  'getZkCurrentRoot' : IDL.Func([], [IDL.Text], ['query']),
  'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initializeAdminAccessControl' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordEmailSend' : IDL.Func([IDL.Text, IDL.Text, EmailStatus], [], []),
  'recordRedemption' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Currency,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'registerMyVessel' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeAuditor' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedUsersDefault' : IDL.Func([], [], []),
  'setCompanyInfo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'setTokenomics' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'submitCareerInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitInvestorInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitQuizAttempt' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
      [QuizAttempt],
      [],
    ),
  'submitStcwQuiz' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [
        IDL.Record({
          'vesselsUnlocked' : IDL.Nat,
          'score' : IDL.Nat,
          'passed' : IDL.Bool,
        }),
      ],
      [],
    ),
  'toggleUniversalLaunch' : IDL.Func([], [], []),
  'updateGiftCardStatus' : IDL.Func([IDL.Text, Status], [], []),
  'updateQuestion' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateQuiz' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateShipmentStatus' : IDL.Func(
      [IDL.Text, ShipmentStatus, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'validatePrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'voteOnProposal' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CargoItem = IDL.Record({
    'id' : IDL.Text,
    'weight' : IDL.Float64,
    'containerNumber' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const ExportMethod = IDL.Variant({
    'csv' : IDL.Null,
    'pdf' : IDL.Null,
    'excel' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Currency = IDL.Variant({
    'btc' : IDL.Null,
    'eth' : IDL.Null,
    'eur' : IDL.Null,
    'gbp' : IDL.Null,
    'usd' : IDL.Null,
    'bgkd' : IDL.Null,
  });
  const GiftCardType = IDL.Variant({
    'fiat' : IDL.Null,
    'hybrid' : IDL.Null,
    'crypto' : IDL.Null,
  });
  const Time = IDL.Int;
  const AIStatus = IDL.Record({
    'status' : IDL.Text,
    'lastUpdated' : Time,
    'error' : IDL.Opt(IDL.Text),
    'currentTask' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'difficulty' : IDL.Text,
    'explanation' : IDL.Text,
    'questionText' : IDL.Text,
    'subjectId' : IDL.Text,
    'courseId' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'topicId' : IDL.Text,
  });
  const Quiz = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'passingScore' : IDL.Nat,
    'timeLimitMinutes' : IDL.Nat,
    'questionIds' : IDL.Vec(IDL.Text),
    'courseId' : IDL.Text,
  });
  const LocationUpdate = IDL.Record({
    'status' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'location' : IDL.Text,
  });
  const ShipmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'inTransit' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Shipment = IDL.Record({
    'id' : IDL.Text,
    'trackingTimeline' : IDL.Vec(LocationUpdate),
    'cargoDetails' : IDL.Vec(CargoItem),
    'originPort' : IDL.Text,
    'requester' : IDL.Text,
    'assignedBy' : IDL.Text,
    'departureDate' : Time,
    'vesselId' : IDL.Text,
    'createdAt' : Time,
    'customsDocumentation' : IDL.Text,
    'destinationPort' : IDL.Text,
    'estimatedArrivalDate' : Time,
    'updatedAt' : Time,
    'currentStatus' : ShipmentStatus,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'updatedAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const CareerInquiry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const CompanyInfo = IDL.Record({
    'leadershipQuote' : IDL.Text,
    'metrics' : IDL.Record({
      'vessels' : IDL.Nat,
      'crew' : IDL.Nat,
      'countries' : IDL.Nat,
      'years' : IDL.Nat,
    }),
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ConnectionStatus = IDL.Record({
    'status' : IDL.Text,
    'ping' : IDL.Opt(IDL.Int),
    'network' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'environment' : IDL.Text,
    'canisterId' : IDL.Text,
    'retries' : IDL.Nat,
  });
  const ContactForm = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const DAOProposal = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'votesAgainst' : IDL.Nat,
    'votesFor' : IDL.Nat,
    'createdAt' : Time,
    'votingDeadline' : Time,
    'description' : IDL.Text,
  });
  const AnalyticsData = IDL.Record({
    'totalValue' : IDL.Nat,
    'countriesActive' : IDL.Nat,
    'activeCards' : IDL.Nat,
    'redemptionRate' : IDL.Float64,
  });
  const Status = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'redeemed' : IDL.Null,
  });
  const ExportRecord = IDL.Record({
    'id' : IDL.Text,
    'method' : ExportMethod,
    'user' : IDL.Text,
    'timestamp' : Time,
    'cardId' : IDL.Text,
  });
  const Export = IDL.Record({
    'id' : IDL.Text,
    'method' : ExportMethod,
    'user' : IDL.Text,
    'timestamp' : Time,
    'cardId' : IDL.Text,
  });
  const EmailStatus = IDL.Variant({
    'pending' : IDL.Null,
    'sent' : IDL.Null,
    'delivered' : IDL.Null,
    'failed' : IDL.Null,
    'bounced' : IDL.Null,
  });
  const Email = IDL.Record({
    'id' : IDL.Text,
    'to' : IDL.Text,
    'status' : EmailStatus,
    'timestamp' : Time,
    'cardId' : IDL.Text,
  });
  const EmailRecord = IDL.Record({
    'id' : IDL.Text,
    'to' : IDL.Text,
    'status' : EmailStatus,
    'timestamp' : Time,
    'cardId' : IDL.Text,
  });
  const Redemption = IDL.Record({
    'redeemedBy' : IDL.Text,
    'deviceDetails' : IDL.Text,
    'verificationData' : IDL.Text,
    'currency' : Currency,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
    'location' : IDL.Text,
  });
  const GiftCard = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'exportHistory' : IDL.Vec(ExportRecord),
    'exports' : IDL.Vec(Export),
    'value' : IDL.Nat,
    'termsAccepted' : IDL.Bool,
    'owner' : IDL.Text,
    'cardType' : GiftCardType,
    'redemptionCount' : IDL.Nat,
    'code' : IDL.Text,
    'analyticsData' : IDL.Opt(AnalyticsData),
    'createdAt' : Time,
    'creationMetadata' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'emails' : IDL.Vec(Email),
    'lastUpdatedBy' : IDL.Text,
    'updatedAt' : Time,
    'emailHistory' : IDL.Vec(EmailRecord),
    'expirationDate' : Time,
    'barcode' : IDL.Text,
    'currency' : Currency,
    'notes' : IDL.Text,
    'originCountry' : IDL.Text,
    'redemptionHistory' : IDL.Vec(Redemption),
    'copiesGenerated' : IDL.Nat,
    'qrCode' : IDL.Text,
  });
  const InvestorInquiry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ShipVessel = IDL.Record({
    'id' : IDL.Nat,
    'telemetry' : IDL.Text,
    'name' : IDL.Text,
  });
  const OmniMeshStatus = IDL.Record({
    'status' : IDL.Text,
    'active' : IDL.Bool,
    'nodes' : IDL.Nat,
    'lastSync' : Time,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'details' : IDL.Text,
  });
  const Tokenomics = IDL.Record({
    'roadmap' : IDL.Text,
    'complianceNotice' : IDL.Text,
    'utility' : IDL.Text,
    'contractLink' : IDL.Text,
    'totalSupply' : IDL.Nat,
    'whitepaperLink' : IDL.Text,
    'governance' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const TreasuryStatus = IDL.Record({
    'currencyBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalValue' : IDL.Nat,
    'liquidity' : IDL.Float64,
    'reserves' : IDL.Nat,
    'lastAudit' : Time,
  });
  const QuizAttempt = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Text,
    'score' : IDL.Float64,
    'attemptDate' : IDL.Int,
    'selectedAnswers' : IDL.Vec(IDL.Nat),
    'quizId' : IDL.Text,
    'passed' : IDL.Bool,
  });
  const Vessel = IDL.Record({
    'id' : IDL.Text,
    'vesselType' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'capacity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAuditor' : IDL.Func([IDL.Text], [], []),
    'addCargoItem' : IDL.Func([IDL.Text, CargoItem], [], []),
    'addExportRecord' : IDL.Func([IDL.Text, ExportMethod, IDL.Text], [], []),
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addVessel' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(ExternalBlob),
          IDL.Text,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGiftCard' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Currency,
          GiftCardType,
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createQuestion' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createQuiz' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'createShipment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(CargoItem),
          Time,
          Time,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteQuestion' : IDL.Func([IDL.Text], [], []),
    'deleteQuiz' : IDL.Func([IDL.Text], [], []),
    'generateZkSolvencyProof' : IDL.Func([], [IDL.Text], []),
    'getAIStatus' : IDL.Func([], [AIStatus], ['query']),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getAllQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
    'getAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterInfo' : IDL.Func([], [IDL.Text], ['query']),
    'getCareerInquiries' : IDL.Func([], [IDL.Vec(CareerInquiry)], ['query']),
    'getCompanyInfo' : IDL.Func([], [IDL.Opt(CompanyInfo)], ['query']),
    'getConnectionStatus' : IDL.Func([], [ConnectionStatus], ['query']),
    'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getDaoProposals' : IDL.Func([], [IDL.Vec(DAOProposal)], ['query']),
    'getGiftCardAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
    'getGiftCardById' : IDL.Func([IDL.Text], [IDL.Opt(GiftCard)], ['query']),
    'getGiftCards' : IDL.Func([], [IDL.Vec(GiftCard)], ['query']),
    'getInvestorInquiries' : IDL.Func(
        [],
        [IDL.Vec(InvestorInquiry)],
        ['query'],
      ),
    'getMyVessels' : IDL.Func([], [IDL.Vec(ShipVessel)], ['query']),
    'getNetworkInfo' : IDL.Func([], [IDL.Text], ['query']),
    'getOmniMeshStatus' : IDL.Func([], [OmniMeshStatus], ['query']),
    'getPublicDemoShips' : IDL.Func([], [IDL.Vec(ShipVessel)], ['query']),
    'getQuestionById' : IDL.Func([IDL.Text], [IDL.Opt(Question)], ['query']),
    'getQuestionsByCourse' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuizById' : IDL.Func([IDL.Text], [IDL.Opt(Quiz)], ['query']),
    'getQuizzesByCourse' : IDL.Func([IDL.Text], [IDL.Vec(Quiz)], ['query']),
    'getRegistryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getShipmentById' : IDL.Func([IDL.Text], [IDL.Opt(Shipment)], ['query']),
    'getShipmentsByVessel' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Shipment)],
        ['query'],
      ),
    'getTokenomics' : IDL.Func([], [IDL.Opt(Tokenomics)], ['query']),
    'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getTreasuryStatus' : IDL.Func([], [TreasuryStatus], ['query']),
    'getUniversalLaunchState' : IDL.Func([], [IDL.Bool], ['query']),
    'getUserAttempts' : IDL.Func([IDL.Text], [IDL.Vec(QuizAttempt)], ['query']),
    'getUserById' : IDL.Func([IDL.Nat], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVessels' : IDL.Func([], [IDL.Vec(Vessel)], ['query']),
    'getVesselsByType' : IDL.Func([IDL.Text], [IDL.Vec(Vessel)], ['query']),
    'getZkCurrentRoot' : IDL.Func([], [IDL.Text], ['query']),
    'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeAdminAccessControl' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordEmailSend' : IDL.Func([IDL.Text, IDL.Text, EmailStatus], [], []),
    'recordRedemption' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Currency,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'registerMyVessel' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeAuditor' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedUsersDefault' : IDL.Func([], [], []),
    'setCompanyInfo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'setTokenomics' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'submitCareerInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitInvestorInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitQuizAttempt' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
        [QuizAttempt],
        [],
      ),
    'submitStcwQuiz' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [
          IDL.Record({
            'vesselsUnlocked' : IDL.Nat,
            'score' : IDL.Nat,
            'passed' : IDL.Bool,
          }),
        ],
        [],
      ),
    'toggleUniversalLaunch' : IDL.Func([], [], []),
    'updateGiftCardStatus' : IDL.Func([IDL.Text, Status], [], []),
    'updateQuestion' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateQuiz' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateShipmentStatus' : IDL.Func(
        [IDL.Text, ShipmentStatus, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'validatePrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'voteOnProposal' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };