/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIStatus {
  'status' : string,
  'lastUpdated' : Time,
  'error' : [] | [string],
  'currentTask' : string,
}
export interface AnalyticsData {
  'totalValue' : bigint,
  'countriesActive' : bigint,
  'activeCards' : bigint,
  'redemptionRate' : number,
}
export interface CareerInquiry {
  'id' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface CargoItem {
  'id' : string,
  'weight' : number,
  'containerNumber' : string,
  'description' : string,
  'quantity' : bigint,
}
export interface CompanyInfo {
  'leadershipQuote' : string,
  'metrics' : {
    'vessels' : bigint,
    'crew' : bigint,
    'countries' : bigint,
    'years' : bigint,
  },
  'tagline' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface ConnectionStatus {
  'status' : string,
  'ping' : [] | [bigint],
  'network' : string,
  'message' : string,
  'timestamp' : Time,
  'environment' : string,
  'canisterId' : string,
  'retries' : bigint,
}
export interface ContactForm {
  'id' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type Currency = { 'btc' : null } |
  { 'eth' : null } |
  { 'eur' : null } |
  { 'gbp' : null } |
  { 'usd' : null } |
  { 'bgkd' : null };
export interface DAOProposal {
  'id' : string,
  'status' : string,
  'title' : string,
  'votesAgainst' : bigint,
  'votesFor' : bigint,
  'createdAt' : Time,
  'votingDeadline' : Time,
  'description' : string,
}
export interface Email {
  'id' : string,
  'to' : string,
  'status' : EmailStatus,
  'timestamp' : Time,
  'cardId' : string,
}
export interface EmailRecord {
  'id' : string,
  'to' : string,
  'status' : EmailStatus,
  'timestamp' : Time,
  'cardId' : string,
}
export type EmailStatus = { 'pending' : null } |
  { 'sent' : null } |
  { 'delivered' : null } |
  { 'failed' : null } |
  { 'bounced' : null };
export interface Export {
  'id' : string,
  'method' : ExportMethod,
  'user' : string,
  'timestamp' : Time,
  'cardId' : string,
}
export type ExportMethod = { 'csv' : null } |
  { 'pdf' : null } |
  { 'excel' : null };
export interface ExportRecord {
  'id' : string,
  'method' : ExportMethod,
  'user' : string,
  'timestamp' : Time,
  'cardId' : string,
}
export type ExternalBlob = Uint8Array;
export interface GiftCard {
  'id' : string,
  'status' : Status,
  'exportHistory' : Array<ExportRecord>,
  'exports' : Array<Export>,
  'value' : bigint,
  'termsAccepted' : boolean,
  'owner' : string,
  'cardType' : GiftCardType,
  'redemptionCount' : bigint,
  'code' : string,
  'analyticsData' : [] | [AnalyticsData],
  'createdAt' : Time,
  'creationMetadata' : string,
  'mobileNumber' : string,
  'emails' : Array<Email>,
  'lastUpdatedBy' : string,
  'updatedAt' : Time,
  'emailHistory' : Array<EmailRecord>,
  'expirationDate' : Time,
  'barcode' : string,
  'currency' : Currency,
  'notes' : string,
  'originCountry' : string,
  'redemptionHistory' : Array<Redemption>,
  'copiesGenerated' : bigint,
  'qrCode' : string,
}
export type GiftCardType = { 'fiat' : null } |
  { 'hybrid' : null } |
  { 'crypto' : null };
export interface InvestorInquiry {
  'id' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface LocationUpdate {
  'status' : string,
  'notes' : string,
  'timestamp' : Time,
  'location' : string,
}
export interface OmniMeshStatus {
  'status' : string,
  'active' : boolean,
  'nodes' : bigint,
  'lastSync' : Time,
}
export interface Question {
  'id' : string,
  'correctIndex' : bigint,
  'difficulty' : string,
  'explanation' : string,
  'questionText' : string,
  'subjectId' : string,
  'courseId' : string,
  'options' : Array<string>,
  'topicId' : string,
}
export interface Quiz {
  'id' : string,
  'title' : string,
  'passingScore' : bigint,
  'timeLimitMinutes' : bigint,
  'questionIds' : Array<string>,
  'courseId' : string,
}
export interface QuizAttempt {
  'id' : string,
  'userId' : string,
  'score' : number,
  'attemptDate' : bigint,
  'selectedAnswers' : Array<bigint>,
  'quizId' : string,
  'passed' : boolean,
}
export interface Redemption {
  'redeemedBy' : string,
  'deviceDetails' : string,
  'verificationData' : string,
  'currency' : Currency,
  'notes' : string,
  'timestamp' : Time,
  'amount' : bigint,
  'location' : string,
}
export interface Service {
  'id' : string,
  'name' : string,
  'description' : string,
  'details' : string,
}
export interface ShipVessel {
  'id' : bigint,
  'telemetry' : string,
  'name' : string,
}
export interface Shipment {
  'id' : string,
  'trackingTimeline' : Array<LocationUpdate>,
  'cargoDetails' : Array<CargoItem>,
  'originPort' : string,
  'requester' : string,
  'assignedBy' : string,
  'departureDate' : Time,
  'vesselId' : string,
  'createdAt' : Time,
  'customsDocumentation' : string,
  'destinationPort' : string,
  'estimatedArrivalDate' : Time,
  'updatedAt' : Time,
  'currentStatus' : ShipmentStatus,
}
export type ShipmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'inTransit' : null } |
  { 'delivered' : null };
export type Status = { 'active' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'redeemed' : null };
export type Time = bigint;
export interface Tokenomics {
  'roadmap' : string,
  'complianceNotice' : string,
  'utility' : string,
  'contractLink' : string,
  'totalSupply' : bigint,
  'whitepaperLink' : string,
  'governance' : string,
  'symbol' : string,
}
export interface TreasuryStatus {
  'currencyBreakdown' : Array<[string, bigint]>,
  'totalValue' : bigint,
  'liquidity' : number,
  'reserves' : bigint,
  'lastAudit' : Time,
}
export interface User {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'updatedAt' : Time,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vessel {
  'id' : string,
  'vesselType' : string,
  'name' : string,
  'description' : string,
  'image' : [] | [ExternalBlob],
  'capacity' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAuditor' : ActorMethod<[string], undefined>,
  'addCargoItem' : ActorMethod<[string, CargoItem], undefined>,
  'addExportRecord' : ActorMethod<[string, ExportMethod, string], undefined>,
  'addService' : ActorMethod<[string, string, string, string], undefined>,
  'addUser' : ActorMethod<[string, string], undefined>,
  'addVessel' : ActorMethod<
    [string, string, string, bigint, [] | [ExternalBlob], string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGiftCard' : ActorMethod<
    [
      string,
      string,
      bigint,
      Currency,
      GiftCardType,
      string,
      string,
      Time,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'createQuestion' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      bigint,
      string,
      string,
    ],
    undefined
  >,
  'createQuiz' : ActorMethod<
    [string, string, string, Array<string>, bigint, bigint],
    undefined
  >,
  'createShipment' : ActorMethod<
    [string, string, string, Array<CargoItem>, Time, Time, string, string],
    undefined
  >,
  'deleteQuestion' : ActorMethod<[string], undefined>,
  'deleteQuiz' : ActorMethod<[string], undefined>,
  'generateZkSolvencyProof' : ActorMethod<[], string>,
  'getAIStatus' : ActorMethod<[], AIStatus>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getAllQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getAllShipments' : ActorMethod<[], Array<Shipment>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterInfo' : ActorMethod<[], string>,
  'getCareerInquiries' : ActorMethod<[], Array<CareerInquiry>>,
  'getCompanyInfo' : ActorMethod<[], [] | [CompanyInfo]>,
  'getConnectionStatus' : ActorMethod<[], ConnectionStatus>,
  'getContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getCyclesBalance' : ActorMethod<[], bigint>,
  'getDaoProposals' : ActorMethod<[], Array<DAOProposal>>,
  'getGiftCardAnalytics' : ActorMethod<[], AnalyticsData>,
  'getGiftCardById' : ActorMethod<[string], [] | [GiftCard]>,
  'getGiftCards' : ActorMethod<[], Array<GiftCard>>,
  'getInvestorInquiries' : ActorMethod<[], Array<InvestorInquiry>>,
  'getMyVessels' : ActorMethod<[], Array<ShipVessel>>,
  'getNetworkInfo' : ActorMethod<[], string>,
  'getOmniMeshStatus' : ActorMethod<[], OmniMeshStatus>,
  'getPublicDemoShips' : ActorMethod<[], Array<ShipVessel>>,
  'getQuestionById' : ActorMethod<[string], [] | [Question]>,
  'getQuestionsByCourse' : ActorMethod<[string], Array<Question>>,
  'getQuizById' : ActorMethod<[string], [] | [Quiz]>,
  'getQuizzesByCourse' : ActorMethod<[string], Array<Quiz>>,
  'getRegistryCount' : ActorMethod<[], bigint>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getShipmentById' : ActorMethod<[string], [] | [Shipment]>,
  'getShipmentsByVessel' : ActorMethod<[string], Array<Shipment>>,
  'getTokenomics' : ActorMethod<[], [] | [Tokenomics]>,
  'getTotalUsers' : ActorMethod<[], bigint>,
  'getTreasuryStatus' : ActorMethod<[], TreasuryStatus>,
  'getUniversalLaunchState' : ActorMethod<[], boolean>,
  'getUserAttempts' : ActorMethod<[string], Array<QuizAttempt>>,
  'getUserById' : ActorMethod<[bigint], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVessels' : ActorMethod<[], Array<Vessel>>,
  'getVesselsByType' : ActorMethod<[string], Array<Vessel>>,
  'getZkCurrentRoot' : ActorMethod<[], string>,
  'healthCheck' : ActorMethod<[], string>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initializeAdminAccessControl' : ActorMethod<[Array<string>], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordEmailSend' : ActorMethod<[string, string, EmailStatus], undefined>,
  'recordRedemption' : ActorMethod<
    [string, string, bigint, Currency, string, string, string, string],
    undefined
  >,
  'registerMyVessel' : ActorMethod<[string], boolean>,
  'removeAuditor' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedUsersDefault' : ActorMethod<[], undefined>,
  'setCompanyInfo' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
    ],
    undefined
  >,
  'setTokenomics' : ActorMethod<
    [bigint, string, string, string, string, string, string, string],
    undefined
  >,
  'submitCareerInquiry' : ActorMethod<[string, string, string], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'submitInvestorInquiry' : ActorMethod<[string, string, string], undefined>,
  'submitQuizAttempt' : ActorMethod<
    [string, string, Array<bigint>],
    QuizAttempt
  >,
  'submitStcwQuiz' : ActorMethod<
    [Array<bigint>],
    { 'vesselsUnlocked' : bigint, 'score' : bigint, 'passed' : boolean }
  >,
  'toggleUniversalLaunch' : ActorMethod<[], undefined>,
  'updateGiftCardStatus' : ActorMethod<[string, Status], undefined>,
  'updateQuestion' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      bigint,
      string,
      string,
    ],
    undefined
  >,
  'updateQuiz' : ActorMethod<
    [string, string, string, Array<string>, bigint, bigint],
    undefined
  >,
  'updateShipmentStatus' : ActorMethod<
    [string, ShipmentStatus, string, string],
    undefined
  >,
  'validatePrincipal' : ActorMethod<[Principal], boolean>,
  'voteOnProposal' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];